order_up/app/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()

class Employee(db.Model, UserMixin):
  __tablename__ = 'employees'

  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(100), nullable=False)
  employee_number = db.Column(db.Integer, nullable=False, unique=True)
  hashed_password = db.Column(db.String(255), nullable=False)

  orders = db.relationship('Order', back_populates='employee')


  @property
  def password(self):
    return self.hashed_password

  @password.setter
  def password(self, password):
    self.hashed_password = generate_password_hash(password)

  def check_password(self, password):
    return check_password_hash(self.password, password)

class Menu(db.Model):
  __tablename__ = 'menus'

  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(30), nullable=False)

  items = db.relationship('MenuItem', back_populates='menu')

class MenuItem(db.Model):
  __tablename__ = 'menu_items'

  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(50), nullable=False)
  price = db.Column(db.Float, nullable=False)
  menu_id = db.Column(db.Integer, db.ForeignKey('menus.id'), nullable=False)
  menu_type_id = db.Column(db.Integer, db.ForeignKey('menu_item_types.id'), nullable=False)

  menu = db.relationship('Menu', back_populates='items')
  type = db.relationship('MenuItemType')


class MenuItemType(db.Model):
  __tablename__ = 'menu_item_types'

  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(20), nullable=False)

  # type = db.relationship('MenuItemType', back_populates='type')


class Table(db.Model):
  __tablename__ = 'tables'

  id = db.Column(db.Integer, primary_key=True)
  number = db.Column(db.Integer, nullable=False, unique=True)
  capacity = db.Column(db.Integer, nullable=False)

  orders = db.relationship('Order', back_populates='table')


class Order(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  employee_id = db.Column(db.Integer, db.ForeignKey('employees.id'), nullable=False)
  table_id = db.Column(db.Integer, db.ForeignKey('tables.id'), nullable=False)
  finished = db.Column(db.Boolean, nullable=False)

  employee = db.relationship('Employee', back_populates='orders')
  table = db.relationship('Table', back_populates='orders')


class OrderDetail(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  order_id = db.Column(db.Integer, db.ForeignKey('order.id'), nullable=False)
  menu_item_id = db.Column(db.Integer, db.ForeignKey('menu_items.id'), nullable=False)

order_up/app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, ValidationError

class LoginForm(FlaskForm):
  employee_number = StringField('Employee Number', validators=[DataRequired()])
  password = PasswordField('Password', validators=[DataRequired()])
  submit = SubmitField('Submit')

order_up/app/__init__.py
from flask import Flask
from .config import Configuration
from .routes import orders
from .routes import session
from app.models import db, Employee
from flask_login import LoginManager

app = Flask(__name__)
app.config.from_object(Configuration)
app.register_blueprint(orders.bp)
app.register_blueprint(session.bp)
db.init_app(app)

login = LoginManager(app)
login.login_view = 'session.login'

@login.user_loader
def load_user(id):
  return Employee.query.get(int(id))

order_up/app/routes/orders.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

bp = Blueprint('orders', __name__, url_prefix='')

@bp.route('/')
@login_required
def index():
  return render_template('orders.html', current_user= current_user)

order_up/app/routes/session.py
from flask import Blueprint, render_template, redirect, url_for
from app.forms import LoginForm
from app.models import Employee
from flask_login import current_user, login_user, logout_user


bp = Blueprint('session', __name__, url_prefix='/session')

@bp.route("/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("orders.index"))
    form = LoginForm()
    if form.validate_on_submit():
        empl_number = form.employee_number.data
        employee = Employee.query.filter(Employee.employee_number == empl_number).first()
        if not employee or not employee.check_password(form.password.data):
            return redirect(url_for(".login"))
        login_user(employee)
        return redirect(url_for("orders.index"))
    return render_template("login.html", form=form, current_user = current_user)


@bp.route('/logout', methods=["POST"])
def logout():
    logout_user()
    return redirect(url_for('.login'))

order_up/app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% if title %}
      <title>{{ title }} - Order Up!</title>
    {% else %}
      <title>Welcome to Order Up!</title>
    {% endif %}
  </head>
  <body>
    {% block content %}{% endblock %}
    <form method="post" action="{{ url_for('session.logout') }}">
      {% if current_user.name %}
      <button>Logout</button>
      {% endif %}
    </form>
  </body>
</html>

order_up/app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<form method="post" action="{{ url_for('.login') }}">
  {{ form.csrf_token }}
  <div>
    {{ form.employee_number.label }} {{ form.employee_number }}

    {% if form.employee_number.errors %}
      <ul>
        {% for error in form.employee_number.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
  <div>
    {{ form.password.label }} {{ form.password }}

    {% if form.employee_number.errors %}
      <ul>
        {% for error in form.employee_number.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
  <div>{{ form.submit }}</div>
</form>
{% endblock %}

order_up/app/templates/orders.html
{% extends 'base.html' %}

{% block content %}
  <h1>Order Up!</h1>
{% endblock %}